language: python
python: 3.5
env:
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=py36
install:
    - pip install tox -r requirements.txt
script:
    - tox -e $TOX_ENV
sudo: false