version: '2'

services:
  web:
    environment:
      - DEBUG=False
      - SECRET_KEY='h8*!auo41coamji#&6lly40%&r&4+s_b#bc8!dqpz3hxdq_*vh'
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  webserver:
    image: jumanjiman/caddy
    depends_on:
      - web
    ports:
      - "80:8000"
    command: -port 8000 -host 0.0.0.0 "proxy / web:8000 { }"
